// NOTE: before proceeding further, it is recommended you learn about the programmable graphics pipeline.
// To know more about the programmable graphics pipeline please visit this website:
// http://duriansoftware.com/joe/An-intro-to-modern-OpenGL.-Chapter-1:-The-Graphics-Pipeline.html

// The fragment shader is a shader that processes the fragment generated by the rasterization
// into a set of colors and single depth value

#version 330 core

in vec3 ourColor;

out vec4 color;

void main()
{
	color = vec4(ourColor, 1.0f);
}